src/ToG/ForumBundle/Entity/Forum.php
<?php

namespace ToG\ForumBundle\Entity;


use Symfony\Component\Serializer\Serializer;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Serializer\Encoder\XmlEncoder;
use Symfony\Component\Serializer\Encoder\JsonEncoder;
use Symfony\Component\Serializer\Normalizer\ObjectNormalizer;

use Doctrine\ORM\Mapping as ORM;

use ToG\ForumBundle\Utility\Utility;

/**
 * Forum
 *
 * @ORM\Table(name="tog_forum")
 * @ORM\Entity(repositoryClass="ToG\ForumBundle\Repository\ForumRepository")
 */
class Forum
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=255, unique=true)
     */
    private $name;

    /**
     * @var string
     *
     * @ORM\Column(name="description", type="string", length=255, nullable=true)
     */
    private $description;

    /**
     * @var int
     *
     * @ORM\Column(name="parent_id", type="integer", nullable=true)
     */
    private $parentId;

    /**
     * @var int
     *
     * @ORM\Column(name="type", type="integer")
     */
    private $type; // type 0 = categorie, 1 = forum, 2 = forum_link ?

    /**
     * @var string
     *
     * @ORM\Column(name="clean_name", type="string", length=255)
     */
    private $cleanName;

    /**
     * @var array
     */
    private $subForums;

    /**
     * @ORM\OneToMany(targetEntity="Topic", mappedBy="forum")
     */
    private $topics;

    /**
    * @var int
    *
    * @ORM\Column(name="topics_count", type="integer", nullable=true)
    */
    private $topics_count;

    /**
    * @var int
    *
    * @ORM\Column(name="posts_count", type="integer", nullable=true)
    */
    private $posts_count;

    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set name
     *
     * @param string $name
     *
     * @return Forum
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set description
     *
     * @param string $description
     *
     * @return Forum
     */
    public function setDescription($description)
    {
        $this->description = $description;

        return $this;
    }

    /**
     * Get description
     *
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Set parentId
     *
     * @param integer $parentId
     *
     * @return Forum
     */
    public function setParentId($parentId)
    {
        $this->parentId = $parentId;

        return $this;
    }

    /**
     * Get parentId
     *
     * @return int
     */
    public function getParentId()
    {
        return $this->parentId;
    }

    /**
     * Set type
     *
     * @param integer $type
     *
     * @return Forum
     */
    public function setType($type)
    {
        $this->type = $type;

        return $this;
    }

    /**
     * Get type
     *
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Set cleanName
     *
     * @param string $cleanName
     *
     * @return Forum
     */
    public function setCleanName($cleanName)
    {
        $cleanName = Utility::cleanString($cleanName);

        $this->cleanName = $cleanName;

        return $this;
    }

    /**
     * Get cleanName
     *
     * @return string
     */
    public function getCleanName()
    {
        return $this->cleanName;
    }

    /**
     * Set subForums
     *
     * @param array subForums
     *
     * @return Forum
     */
    public function setSubForums($subForums)
    {
        $this->subForums = $subForums;

        return $this;
    }

    /**
     * Get subForums
     *
     * @return Forum
     */
    public function getSubForums()
    {
        return $this->subForums;
    }

    /**
     * Add topic
     *
     * @param \ToG\ForumBundle\Entity\Topic $topic
     *
     * @return Topic
     */
    public function addTopic(\ToG\ForumBundle\Entity\Topic $topic)
    {
        $this->topics[] = $topic;

        return $this;
    }

    /**
     * Remove topic
     *
     * @param \ToG\ForumBundle\Entity\Topic $topic
     */
    public function removeTopic(\ToG\ForumBundle\Entity\Topic $topic)
    {
        $this->topics->removeElement($topic);
    }

    /**
     * Get topics
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getTopics()
    {
        return $this->topics;
    }

    /**
     * Get the value of Topics Count
     *
     * @return int
     */
    public function getTopicsCount()
    {
        return $this->topics_count;
    }

    /**
     * Set the value of Topics Count
     *
     * @param int topics_count
     *
     * @return self
     */
    public function setTopicsCount($topics_count)
    {
        $this->topics_count = $topics_count;

        return $this;
    }

    /**
     * Add +1 to Topics Count
     *
     * @return self
     */
    public function incrementTopicsCount()
    {
        $this->topics_count++;

        return $this;
    }

    /**
     * Get the value of Posts Count
     *
     * @return int
     */
    public function getPostsCount()
    {
        return $this->posts_count;
    }

    /**
     * Set the value of Posts Count
     *
     * @param int posts_count
     *
     * @return self
     */
    public function setPostsCount($posts_count)
    {
        $this->posts_count = $posts_count;

        return $this;
    }

    /**
     * Add +1 to Posts Count
     *
     * @return self
     */
    public function incrementPostsCount()
    {
        $this->posts_count++;

        return $this;
    }   

    public function serialize()
    {        
        $encoder = new JsonEncoder();
        $normalizer = new ObjectNormalizer();
        $normalizer->setIgnoredAttributes(['topics']);

        $serializer = new Serializer([$normalizer], [$encoder]);

        return $serializer->serialize($this, 'json');
    }
}

src/ToG/ForumBundle/Controller/CommonController.php
<?php

namespace ToG\ForumBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use ToG\ForumBundle\Entity\Post;
use ToG\ForumBundle\Entity\Topic;
use ToG\ForumBundle\Form\Type\PostType;
use ToG\RolePlayBundle\Entity\Character;
use ToG\UserBundle\Entity\User;

class CommonController extends Controller
{
    /**
     * Cette méthode raffraîchit le champ last_activity d'un utilisateur à chaque action qu'il entreprend
     * C'est notamment utilisé pour déterminer qui sont les utilisateurs en ligne
     *
     * @param   Object   $user   L'utilisateur connecté
     *
     * @return void
     */
    public function refreshActivity($user)
    {
        $em = $this->getDoctrine()->getManager();

        $newDate = new \DateTime('now');

        $user->setLastActivity($newDate);

        $em->persist($user);
        $em->flush();
    }

    /**
     * La page d'accueil du forum
     *
     * @return view
     */
    public function indexAction()
    {
        $user = $this->getUser();

        if ($user) {
            $characters = $user->getCharacters()->getValues();
            $this->refreshActivity($user);
        }

        $em = $this->getDoctrine();

        $usersRepository = $this->getDoctrine()->getRepository('ToGUserBundle:User');
        $usersOnline = $usersRepository->findUsersOnline();

        foreach ($usersOnline as $user) {
            dump($user);
        }

        $forumRepository = $em->getRepository('ToGForumBundle:Forum');
        $categories_and_forums = $forumRepository->hierarchizeForums();

        $groups = $em->getRepository('ToGRolePlayBundle:Group')
            ->findBy(
                array(),
                array('is_not_rp' => 'ASC')
            );

        foreach ($groups as $group) {
            $members = [];

            foreach ($group->getUserGroupAssociations() as $assoc) {
                $user = $assoc->getUser();
                $members[] = $user;
            }

            foreach ($group->getCharacters() as $character) {
                $members[] = $character;
            }

            $group->setMembers($members);
        }

        return $this->render('ToGForumBundle:Common:index.html.twig', array(
            // Utilisateurs du Qui est en ligne ?
            'usersOnline' => $usersOnline,

            // Liste des catégories et leurs forums
            'categories_and_forums' => $categories_and_forums,

            // Liste des groupes
            'groups' => $groups,
        ));
    }

    /**
     * Page de lecture d'un forum
     *
     * @param  Request    $request     L'objet request
     * @param  integrer   $forumId     L'id du forum
     * @param  string     $cleanName   Le nom SEO du forum
     *
     * @return view
     */
    public function viewForumAction(Request $request, $forumId, $cleanName)
    {
        $user = $this->getUser();

        $em = $this->getDoctrine();

        $forumRepository = $em->getRepository('ToGForumBundle:Forum');
        $forum = $forumRepository->find($forumId);

        $topicRepository = $em->getRepository('ToGForumBundle:Topic');
        $topics = $topicRepository->findBy(
            ['forum' => $forum],
            ['type' => 'DESC', 'lastPostDate' => 'DESC']
        );

        foreach ($topics as $topic) {
            $posts = $topic->getPosts();
            $posts_count = 0;

            foreach ($posts as $post) {
                $posts_count++;
            }

            $topic->setPostsCount($posts_count);
        }

        $post = new Post();
        $topic = new Topic();
        $character = new Character();

        // Si on est dans le forum Créer votre personnage, on ajoute le formulaire dédié
        if ($forum->getName() === 'Créer votre personnage') {
            $groups = $em->getRepository('ToGRolePlayBundle:Group')
                ->findBy(
                    array('is_not_rp' => 0),
                    array('is_not_rp' => 'ASC')
                );

            $newGroups = [];

            foreach ($groups as $group) {
                $newGroups[$group->getId()] = $group;
            }

            $form = $this->createForm(PostType::class, $post, array('new_character' => true, 'groups' => $newGroups));
            $characterCreation = true;
        } else {
            $form = $this->createForm(PostType::class, $post, array('new_topic' => true));
        }

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();

            $date = new \DateTime('now');

            $post = $form->getData();

            if (isset($characterCreation) && $characterCreation) {
                $character = $post->getCharacter();

                if (!empty($character->getAvatar())) {
                    $avatar_directory = $this->container->getParameter('characters_avatars_directory');

                    $avatar = $character->getAvatar();
                    $avatarName = $this->get('app.characters_avatar_uploader')->upload($avatar); // on upload temporairement le nouvel avatar
                    $avatarInfos = getimagesize($avatar_directory . '/' . $avatarName); // on récupère ses informations

                    // si ses dimensions ne sont pas correctes, alors on considère l'upload échoué et on supprime l'avatar
                    if ($avatarInfos[0] !== $avatarInfos[1] || $avatarInfos[0] !== 150) {
                        $failedUpload = true;

                        unlink($avatar_directory . '/' . $avatarName);

                        $character->setAvatar('');
                    }
                }

                $groupId = $character->getGroup();
                $group = $em->getRepository('ToGRolePlayBundle:Group')->find($groupId);

                $character
                    ->setUser($user)
                    ->setGroup($group)
                ;

                if (!empty($_POST['temp_avatar'])) { // si on crop un avatar
                    $avatarName = $_POST['temp_avatar'];
                    $character->setAvatar($avatarName);
                }

                if (!empty($character->getAvatar())) {
                    $character->setAvatar($avatarName);
                }

                $em->persist($character);
                $em->flush();
            }

            // Maintenant, on peut récupérer la partie du form qui nous intéresse : le Topic
            $topic = $post->getTopic();
            $topic
                ->setForum($forum)
                ->setFirstPosterId($user->getId())
                ->setFirstPosterName($user->getUsername())
                ->setLastPosterId($user->getId())
                ->setLastPosterName($user->getUsername())
                ->setType(0) // pour l'instant, un topic est forcément normal
                ->setStatus(1) // pour l'instant, un topic est forcément unlocked
                ->setCleanTitle($topic->getTitle())
                ->setLastPostDate($date)
            ;

            // On enregistre le Topic...
            $em->persist($topic);
            $em->flush();

            // Puis on enregistre le Post en utilisant l'id du Popic
            $post
                ->setUser($user)
                ->setPostDate($date)
            ;

            // On associe le Post au Topic
            $post->setTopic($topic);

            // Puis on met à jour le Topic en utilisant l'id du Post
            $em->persist($post);
            $em->flush();

            $topic->setLastPostId($post->getId());

            $em->flush();

            $forum
                ->incrementTopicsCount()
                ->incrementPostsCount()
            ;

            $em->flush();

            return $this->redirectToRoute('viewtopic', array(
                'topicId' => $topic->getId(),
                'cleanTitle' => $topic->getCleanTitle(),
                '_fragment' => 'post-' . $post->getId(),
            ));
        }

        return $this->render('ToGForumBundle:Common:viewforum.html.twig', array(
            // Titre de la page
            'pageTitle' => $forum->getName(),

            // Données du forum visionné
            'forumData' => $forum,
            'newTopicLabel' => ($forum->getName() === 'Créer votre personnage') ? 'Créer un personnage' : 'Ouvrir un sujet',

            // Liste des sujets du forum visionné
            'topics' => $topics,

            // Formulaire de nouveau sujet
            'form' => $form->createView(),

            // Misc
            'characterCreation' => (isset($characterCreation)) ? true : false,
        ));
    }

    /**
     * Page de lecture d'un sujet
     *
     * @param  Request    $request      L'objet request
     * @param  integrer   $topicId      L'id du sujet consulté
     * @param  string     $cleanTitle   Le titre SEO du sujet
     *
     * @return view
     */
    public function viewTopicAction(Request $request, $topicId, $cleanTitle)
    {
        $user = $this->getUser();

        $topic = $this->getDoctrine()
            ->getRepository('ToGForumBundle:Topic')
            ->find($topicId);

        $forumRepository = $this->getDoctrine()->getRepository('ToGForumBundle:Forum');
        $forum = $forumRepository->find($topic->getForum());

        $posts = $topic->getPosts();

        $userRepository = $this->getDoctrine()->getRepository('ToGUserBundle:User');

        //-- Start : Formulaire de réponse
        //
        $post = new Post();

        $form = $this->createForm(PostType::class, $post);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();

            $date = new \DateTime('now');

            $post = $form->getData();

            $post
                ->setUser($user)
                ->setPostDate($date)
            ;

            // On associe le Post au Topic

src/ToG/ForumBundle/Resources/views/Common/index.html.twig
{% extends 'base.html.twig' %}

{% block javascript %}
{{ dump(categories_and_forums) }}
{% endblock %}

{% block body %}
<main id="page-index">

  <div id="index-root" data-categories-and-forums={{ categories_and_forums|json_encode() }}>
    <forum-list></forum-list>
  </div>

</main>
{% endblock %} 

{% block footer %}
<div class="row">

  <div class="whosonline">

    <h2>Qui est en ligne ?</h2>

    <p>
      {% if usersOnline|length %} Au total, il y a {{ usersOnline|length }} utilisateur{% if usersOnline|length > 1 %}s{% endif
      %} en ligne :
      <ul>
        {% for user in usersOnline %}
        <li>
          <a href="" style="color: #B25D3B">
            <strong>{{ user.username }}</strong>
          </a>{% if loop.last == false %}, {% endif %}</li>
        {% endfor %},
        <li>
          <a href="" style="color: #ec6216">
            <strong>Davoss (Placeholder)</strong>
          </a>
        </li>,
        <li>
          <a href="" style="color: #1675B7">
            <strong>Raltir (Placeholder)</strong>
          </a>
        </li>,
        <li>
          <a href="" style="color: #1675B7">
            <strong>Hana (Placeholder)</strong>
          </a>
        </li>,
        <li>
          <a href="" style="color: #e90707">
            <strong>Andhar (Placeholder)</strong>
          </a>
        </li>,
        <li>
          <a href="" style="color: #7C7C7C">
            <strong>Gilad (Placeholder)</strong>
          </a>
        </li>,
        <li>
          <a href="" style="color: #624079">
            <strong>Ghent (Placeholder)</strong>
          </a>
        </li>
      </ul>
      {% else %} Il n'y a aucun utilisateur connecté actuellement. {% endif %}
    </p>

  </div>

</div>
<!-- /.div row -->

<div class="row">

  <div class="legend">

    <ul>
      {% for group in groups %}
      <li class="faction-{{ group.abreviation }}-border-hover">
        <a href="#" style="color: #{{ group.colour }}">
          <strong>{{ group.name }}</strong>
        </a>
        ({{ group.members|length }})
      </li>
      {% endfor %}
    </ul>

  </div>
  <!-- ./div legend -->

</div>
<!-- /.div row -->
{% endblock %}

src/ToG/ForumBundle/Resources/views/Common/posting.html.twig
{% extends 'base.html.twig' %}

{% block body %}
{% form_theme form 'ToGForumBundle:Form:fields.html.twig' %}
{{ include('ToGForumBundle:Form:bbcode.html.twig') }}

<main id="page-admin">

    <div class="container">

        <div class="row">

            <header class="topic-header">

                <h2 class="topic-title">{{ topicData.title }}</h2>

            </header>

        </div><!-- /.div row -->

        <div class="row">

            {{ form_start(form, { 'attr': {'class': 'form-display1'} }) }}

                {% if mode == 'newTopic' %}
                    {{ form_row(form.topic.title) }}
                {% endif %}

                {{ form_row(form.text) }}

            {{ form_end(form, { 'attr' : { 'class': 'form-posting-msg' } }) }}

        </div><!-- /.div row -->

    </div><!-- /.div container -->

</main>
{% endblock %}

src/ToG/ForumBundle/Resources/views/Common/viewforum.html.twig
{% extends 'base.html.twig' %}

{% block body %}
{% form_theme form 'ToGForumBundle:Form:fields.html.twig' %}
{{ include('ToGForumBundle:Form:bbcode.html.twig') }}

{% javascripts
    'vendors/jcrop/js/jquery.Jcrop.min.js'
    'js/character_creation.js'
    'js/avatar.js'
    output='js/compiled/app.js' %}
<script src="{{ asset_url }}"></script>
{% endjavascripts %}

<script type="text/javascript">
var character_creation_path    = "{{ asset('img/character_creation/groups/') }}";
var update_avatar_by_ajax_path = "{{ path('update_avatar_by_ajax') }}"
var temp_path = "{{ asset('uploads/characters/avatars/') }}";
</script>

<link rel="stylesheet" media="screen" type="text/css" href="{{ asset('vendors/jcrop/css/jquery.Jcrop.min.css') }}" />

<main id="page-viewforum">

    <div class="container">

        <div class="row">

            <header class="forum-header">

                <h2 class="forum-title">{{ forumData.name }}</h2>
                <div class="page-controls">
                    <!-- <input type="text" placeholder="Rechercher" /> -->
                    {% if is_granted('IS_AUTHENTICATED_REMEMBERED') %}
                        <a href="#newtopic" class="button button-type1" id="postingControl"><span class="glyphicon glyphicon-plus"></span>{{ newTopicLabel }}</a>
                    {% endif %}
                </div>

            </header>

        </div><!-- /.div row -->

        <div id="newtopic" class="row">

            {{ form_start(form, { 'attr': {'class': 'form-display1', 'id': 'character-creation'} }) }}

                {{ form_row(form.topic.title) }}

                {% if characterCreation %}
                    <div class="character-creation">
                        {% spaceless %}
                        {{ form_row(form.character.name) }}
                        {{ form_row(form.character.surname) }}
                        {{ form_row(form.character.firstname) }}
                        {{ form_row(form.character.lastname) }}

                        <div class="form-group avatarbox">
                            <img src="{{ asset('img/avatars/no_avatar.jpg') }}" width="150px" height="150px" alt="Avatar manquant" />

                            {{ form_label(form.character.avatar) }} <span class="glyphicon glyphicon-upload label-glyph"></span>

                            <div class="help-block"><span class="glyphicon glyphicon-info-sign"></span> Dimensions minimales : 150px de hauteur, 150px de largeur | Format .JPG</div>

                            {{ form_widget(form.character.avatar, { 'attr': {'class': 'form-control'} }) }}

                            {{ form_errors(form.character.avatar) }}
                        </div>

                        {{ form_row(form.character.gender) }}
                        {{ form_row(form.character.species) }}
                        {{ form_row(form.character.birthdate) }}
                        {{ form_row(form.character.homeworld) }}
                        {{ form_row(form.character.group) }}
                        {{ form_row(form.character.rank) }}
                        {{ form_row(form.character.level) }}
                        {{ form_row(form.character.physical) }}
                        {{ form_row(form.character.mental) }}
                        <input type="hidden" name="temp_avatar" id="temp_avatar">
                        {% endspaceless %}
                    </div>
                {% endif %}

                {{ form_row(form.text) }}

            {{ form_end(form) }}

        </div><!-- /.div row -->

        <div class="topicrow">
            {% for topic in topics %}
                <a href="{{ path('viewtopic', {'topicId': topic.id, 'cleanTitle': topic.cleanTitle}) }}"><div class="row">
                    <div class="topic-title">
                        <span class="glyphicon glyphicon-file" aria-hidden="true"></span>{{ topic.title }}
                    </div>
                    <div class="topic-responses">
                        <span class="glyphicon glyphicon-comment" aria-hidden="true"></span> {{ topic.postsCount }}
                    </div>
                    <div class="topic-author">
                        <strong>{{ topic.firstPosterName }}</strong>
                    </div>
                    <div class="topic-date">
                        {{ topic.lastPostDate|localizeddate('medium', 'none', app.request.locale ) }}
                    </div>
                </div></a>
            {% endfor %}
        </div>

    </div><!-- /.div container -->

</main>
{% endblock %}